# Generated by Django 2.2.7 on 2020-05-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='activity_periods',
            field=models.ManyToManyField(blank=True, to='app1.ActivityPeriod'),
        ),
    ]
