# Generated by Django 2.2.7 on 2020-05-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200526_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='activity_periods',
        ),
        migrations.DeleteModel(
            name='ActivityPeriod',
        ),
    ]
